# roles/kvm_installer_role/handlers.yml
---
- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: false
  listen: "update-grub"

- name: Reboot system
  ansible.builtin.reboot:
    msg: "Rebooting after updating GRUB"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  listen: "reboot-system"
