---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install cockpit
  ansible.builtin.apt:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-pcp
      - cockpit-sosreport
      - cockpit-tests
    state: present
